services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - site1
      - forms-data-handler

  site1:
    build: ./sites/site1
    container_name: site1
    restart: unless-stopped
    # ports:
    #   - "8000:80"
    # volumes:
    #   - ./sites/site1:/usr/share/nginx/html
    networks:
      - app-network
  # site2:
  #   image: nginx:alpine
  #   container_name: site2
  #   restart: unless-stopped
  #   ports:
  #     - "8001:80"
  #   volumes:
  #     - ./sites/site2:/usr/share/nginx/html

  forms-data-handler:
    build: ./forms-data-handler/
    restart: unless-stopped
    # ports: []

    environment:
      - GOOGLE_POST_URL=${GOOGLE_POST_URL}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
