version: '3.8'

services:
  nginx-setup:
    profiles: ["${SETUP_PROFILE:-nginx-setup}"]
    build: 
      context: ./nginx-setup-host
      dockerfile: Dockerfile
    container_name: nginx-setup-host
    volumes:
      - /etc/nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - SITE1_DOMAIN=${SITE1_DOMAIN}
      - SITE2_DOMAIN=${SITE2_DOMAIN}
      - PORT1=8001
      - PORT2=8002
    restart: no
    network_mode: host
    privileged: true

  reverse-proxy:
    profiles: ["${PROXY_PROFILE:-prod}"]
    build: ./reverse-proxy
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8002:8002"
    networks:
      - app-network
    environment:
      - SITE1_DOMAIN=${SITE1_DOMAIN}
      - SITE2_DOMAIN=${SITE2_DOMAIN}
    depends_on:
      - site1
      - site2
      - forms-data-handler

  site1:
    profiles: ["${APP_PROFILE:-prod}"]
    build: ./sites/site1
    container_name: site1
    restart: unless-stopped
    networks:
      - app-network

  site2:
    profiles: ["${APP_PROFILE:-prod}"]
    build: ./sites/site2
    container_name: site2
    restart: unless-stopped
    networks:
      - app-network

  forms-data-handler:
    profiles: ["${APP_PROFILE:-prod}"]
    build: ./forms-data-handler/
    restart: unless-stopped
    environment:
      - GOOGLE_POST_URL=${GOOGLE_POST_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge